@startuml
!theme spacelab

package "Auth Service DB" {

    ' --- TABLA EMPLEADOS ---
    entity "empleados" {
        {PK} empleado_id: SERIAL
        --
        nombre: VARCHAR
        apellido: VARCHAR
        dni: VARCHAR
        telefono: VARCHAR
        rol: VARCHAR
        password: VARCHAR
        user_code: VARCHAR
        estado: BOOLEAN
        --
        fecha_creacion: TIMESTAMP
    }
    
    note right of "empleados"
       **Seguridad:**
       El campo password_hash
       debe ser un HASH (ej. BCrypt),
       nunca texto plano.
    end note

    ' --- TABLA ADMINISTRATIVOS ---
    entity "administrativos" {
        {PK} administrativo_id: SERIAL
        --
        nombre: VARCHAR
        apellido: VARCHAR
        dni: VARCHAR
        telefono: VARCHAR
        rol: VARCHAR
        password: VARCHAR
        user_code: VARCHAR
        estado: BOOLEAN
        --
        fecha_creacion: TIMESTAMP
    }

    note right of "administrativos"
       **Seguridad:**
       Mismo criterio de encriptación
       para administradores.
    end note

}
@enduml